# Generated by Django 5.0 on 2023-12-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_entry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingentry',
            name='status',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=3),
        ),
    ]
